export const paymentjsonone = [
  { id: 1, name: "Visa", Img: "https://logo.clearbit.com/visa.com" },
  { id: 2, name: "Mastercard", Img: "https://logo.clearbit.com/mastercard.com" },
  { id: 3, name: "American Express", Img: "https://logo.clearbit.com/americanexpress.com" },
  { id: 4, name: "Discover", Img: "https://logo.clearbit.com/discover.com" },
  { id: 5, name: "PayPal", Img: "https://logo.clearbit.com/paypal.com" },
  { id: 6, name: "Apple Pay", Img: "https://logo.clearbit.com/apple.com" },
  { id: 7, name: "Google Pay", Img: "https://logo.clearbit.com/pay.google.com" },
  { id: 8, name: "Stripe", Img: "https://logo.clearbit.com/stripe.com" },
  { id: 9, name: "Square", Img: "https://logo.clearbit.com/squareup.com" },
  { id: 10, name: "Alipay", Img: "https://logo.clearbit.com/alipay.com" },
  { id: 11, name: "WeChat Pay", Img: "https://logo.clearbit.com/wechat.com" },
  { id: 12, name: "JCB", Img: "https://logo.clearbit.com/jcb.co.jp" },
  { id: 13, name: "Diners Club", Img: "https://logo.clearbit.com/dinersclub.com" },
];
